### ISSUE TITLE
The MauiMaps references in the README to your customize map pins article, get Web error 404.

### ISSUE THREAD

**Issue by davefxy** [VladislavAntonyuk/MauiSamples#104]
And you might include in the MauiMaps readme that this app will not run on windows. Map control does not appear available on Windows yet and will error out with a navigation error.

**Comment by VladislavAntonyuk** [comment]
I haven't published article yet. I will do it next week.
Maps will work on Windows with .net 7 release. But it will be a part of CommunityToolkit

**Comment by davefxy** [comment]
I am honestly not trying bug you. I noticed these things and commented on them. I do enjoy going over your code. I keep learning new things. Thanks.
