### ISSUE TITLE
[Android]Is it possible to SetIcon when the Pin location is first defined using an extension?

### ISSUE THREAD

**Issue by davefxy** [VladislavAntonyuk/MauiSamples#105]

**Comment by VladislavAntonyuk** [comment]
I didn’t get your question. It displays new icon immediately

**Comment by VladislavAntonyuk** [comment]
For future, please use discussions I’m stead of issues

**Comment by davefxy** [comment]
Sorry. I will. Sent from Mail for Windows From: Vladislav AntonyukSent: Monday, October 10, 2022 1:56 PMTo: VladislavAntonyuk/MauiSamplesCc: Davefxy; AuthorSubject: Re: [VladislavAntonyuk/MauiSamples] [Android]Is it possible to SetIcon when the Pin location is first defined using an extension? (Issue #105) For future, please use discussions I’m stead of issues—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
