### ISSUE TITLE
KanbanBoard Drag doesn't scroll when column is out of screen

### ISSUE THREAD

**Issue by FelipeValentim** [VladislavAntonyuk/MauiSamples#119]
It would be a good a idea to make a scroll to the next column when we get to the edge. But I have no idea how to do that, any idea?

**Comment by VladislavAntonyuk** [comment]
I will take a look.
The idea is the next: subscribe to pointer gesture and depending on its direction set scrolling offset.

**Comment by FelipeValentim** [comment]
What is It a 3rd party lib? Or maybe implemented by custom render?
And I'd like to thanks a lot for that Kanbanboard Sample

**Comment by VladislavAntonyuk** [comment]
I've just implemented it. I will push changes in a few minutes
