### ISSUE TITLE
BottomSheet is not able resize more than half the screen (Android)

### ISSUE THREAD

**Issue by sven-s** [VladislavAntonyuk/MauiSamples#128]
I tested the BottomSheet on Android, but I cannot drag the sheet over the "open bottom sheet" button. Is that not possible? Or is there any parameter setting missing? 

I used an API32 emulator.

**Comment by VladislavAntonyuk** [comment]
For Android I currently set only Content.
I can play with it later. as for the fast solution you can try the code from here: https://stackoverflow.com/questions/50487622/android-bottomsheetdialog-does-not-expand-completely-with-constraintlayout

**Comment by VladislavAntonyuk** [comment]
Updated sample.
In your case you probably need to set `bottomSheetDialog.Behavior.FitToContents = false;` and `bottomSheetDialog.Behavior.MaxHeight=...;`
