### ISSUE TITLE
about db

### ISSUE THREAD

**Issue by BestRockyMen** [VladislavAntonyuk/MauiSamples#13]
i have used your SQLite project and it has been successfully run. Thanks. I have another question to ask. Can Maui connect to the Firebird database?

**Comment by VladislavAntonyuk** [comment]
Hi @BestRockyMen , I do not have experience with Firebird db, but these packages might help you:
- For EntityFrameworkCore: https://www.nuget.org/packages/FirebirdSql.EntityFrameworkCore.Firebird/
- ADO.NET provider: https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient/

**Comment by BestRockyMen** [comment]
ok. Our company tries to use Firebird in PC & phone consistency, so it's under exploration for me. I'll try the link you share. Thanks again
