### ISSUE TITLE
[BUG] Transparent color on Popup not setting correctly in iOS

### ISSUE THREAD

**Issue by AlexanderSCK** [VladislavAntonyuk/MauiSamples#155]
Setting the Popup.Color property on iOS to Transparent doesnt make the Popup Background transparent it stays gray. Appersntly that is because iOS handles page backgrounds differently than Android in terms of transparency, it us unfortunate because it doesnt provide the same look as Android and it becomes unusable. In pursuit curreny of thinking of a workaround. Any suggestions?

**Comment by VladislavAntonyuk** [comment]
It will be fixed by https://github.com/CommunityToolkit/Maui/pull/789
You can apply changes in your project right now
