### ISSUE TITLE
BottomDrawer not working on Android .net-7.0

### ISSUE THREAD

**Issue by edgiardina** [VladislavAntonyuk/MauiSamples#157]
I'm running into two issues trying to get the bottomdrawer example code. First, it seems like `Android.Resources.Content.Id` doesn't exist, at least not in .net 7. 

I've replaced it with `Resource.Id.content`, but I'm not sure 100% that's correct.

Second, is I am getting an exception with getTheme() at runtime when the bottom sheet is trying to open

![image](https://user-images.githubusercontent.com/3627193/204100452-990d3e7b-e0c2-4d3b-9d8c-38210a2016b7.png)

```Java.Lang.NullPointerException
  Message=Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference```

**Comment by VladislavAntonyuk** [comment]
The first problem is with your namespace. It contains Android which conflicts with "Android.Resources"

**Comment by edgiardina** [comment]
You were correct. I've renamed my namespace droid to avoid this. 

Instead of declaring my bottomsheet content in the Resources as a datatemplate, I tried passing an entire new Page() to the function. It works, but the bottomsheet's height is not correct (too tall), likely because the new page renders after its been passed to the bottom sheet and not before by calling CreateContent(). Is there a way to have a page call CreateContent?

**Comment by VladislavAntonyuk** [comment]
The flow is next. 
You init bottom sheet.
Convert MauiPage to Android page by calling ToPlatform
You set content of bottom sheet.
You display bottom sheet. 

I recommend you add a scroll view to your MauiPage. Also play with bottom sheet settings
