### ISSUE TITLE
AuthService not found

### ISSUE THREAD

**Issue by FatCodeMonkey** [VladislavAntonyuk/MauiSamples#158]
Hi,
I have downloaded the whole solution and it works on Windows but when I run on the Android 33 emulator, I get this error:

System.IO.FileNotFoundException: 'Could not load file or assembly 'AuthServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.'

**Comment by VladislavAntonyuk** [comment]
Try to rebuild the project.
Check the path to the project. it should be  in `MauiSamples/Auth/AuthServices`
