### ISSUE TITLE
[iOS] Customizing Map Pins removes the Marker Click events

### ISSUE THREAD

**Issue by jenyangk** [VladislavAntonyuk/MauiSamples#159]
Hello, after following your guide on how to customize Map pins, I noticed that my `MarkerClicked` events are overwritten/missing. I can't seem to figure out how re-add them. The click events work when using the default map pin.

Tested on iOS 16.1.

**Comment by VladislavAntonyuk** [comment]
Could you please attach a small repro?

**Comment by jenyangk** [comment]
@VladislavAntonyuk, here you go: https://github.com/jenyangk/MapPinSample

Please do let me know if you run into any issues with the project. Also note that I have changed `annotationView.CanShowCallout` from `true` to `false` since I only want the marker click event and not show the info window.

Thanks.

**Comment by VladislavAntonyuk** [comment]
fixed by https://github.com/VladislavAntonyuk/MauiSamples/commit/6da5c38efafebba180ab1100f501d46df51498ab

The article is updated as well
