### ISSUE TITLE
How can we change the background color for android botom dialog to transparent ?

### ISSUE THREAD

**Issue by AswinPG** [VladislavAntonyuk/MauiSamples#166]
Is it possible to change the background of the bottom sheet to transparent so that we can style the sheet with maui controls... (eg - Corner radius with Border). Thanks :)

**Comment by VladislavAntonyuk** [comment]
I suggest you use CommunityToolkit.MAUI Popup control.

It supports Color Transparent.

If you still want use BottomSheet, I need to see how to implement it.

**Comment by VladislavAntonyuk** [comment]
I won't add it to sample, but you can find the answer here: https://stackoverflow.com/questions/37104960/bottomsheetdialog-with-transparent-background

**Comment by AswinPG** [comment]
Thanks @VladislavAntonyuk I was able to make it transparent. 

        `public class CustomBottomSheet : BottomSheetDialogFragment
    {
        IView mauiView;
        public CustomBottomSheet(IView mauiView)
        {
            this.mauiView = mauiView;
        }
        public override Dialog OnCreateDialog(Bundle savedInstanceState)
        {
            return base.OnCreateDialog(savedInstanceState);
        }
        public override void SetupDialog(Dialog dialog, int style)
        {

            var page = Shell.Current.CurrentPage;
            dialog.SetContentView(mauiView.ToPlatform(page.Handler?.MauiContext ?? throw new Exception("MauiContext is null")));


            FrameLayout frameLayout = (FrameLayout)dialog.Window.FindViewById(Resource.Id.design_bottom_sheet);
            

            //frameLayout.SetPadding(40, 40, 40, 40);
            frameLayout.SetBackgroundResource(Resource.Color.Transparent);
            frameLayout.SetBackgroundDrawable(new ColorDrawable(Color.Transparent));
            frameLayout.BackgroundTintMode = PorterDuff.Mode.Clear;
            frameLayout.BackgroundTintList = ColorStateList.ValueOf(Color.Transparent);
            frameLayout.SetBackgroundColor(Color.Transparent);

            base.SetupDialog(dialog, style);
        }
    }`
