### ISSUE TITLE
Maui - Auth

### ISSUE THREAD

**Issue by Depechie** [VladislavAntonyuk/MauiSamples#18]
Hey,

I'm trying out your sample https://github.com/VladislavAntonyuk/MauiSamples/blob/main/Auth/MauiAuth but no matter what I try, each time I attempt to login through the web redirect on Android I get the notification: `unauthorized_client: The cllient does not exist or is not enabled for consumers.`

I guess I need to tweak something in Azure on the app registration, but I do not know what. I think I have the correct redirect url's enabled.

Any tips?

**Comment by VladislavAntonyuk** [comment]
Hey,

Make sure you have correctly setup the client on Azure.

1. Create an app and setup Mobile and Desktop applications platform.
2. Make sure you checked the redirect link (it starts with msal)
3. Scroll down on the same page and set Allow public client flows to true.

**Comment by Depechie** [comment]
<img width="1051" alt="Screenshot 2022-05-18 at 23 02 05" src="https://user-images.githubusercontent.com/351693/169155203-2eef2ba7-0ddd-4851-80f5-f36666b23008.png">
I thought I did that all :/

**Comment by VladislavAntonyuk** [comment]
Try to uncheck the first two redirect links so msal be the only one.

**Comment by Depechie** [comment]
No luck :/ thx for the tips by the way, but somehow my setup won't allow login.

**Comment by VladislavAntonyuk** [comment]
Ok, I will try from scratch on weekends. Maybe something has changed sense I published it.

**Comment by Depechie** [comment]
That would be nice!
Still could be something is wrong on my Azure site.

Anyhow a guide on the settings there would be awesome ;)

**Comment by hallqvist** [comment]
I agree, a guide or script for the azure side would be really nice! 

And thank you for great tutorials 😀

**Comment by VladislavAntonyuk** [comment]
https://youtu.be/sTPWF2O456U

**Comment by Depechie** [comment]
Awesome video! And this setup does indeed work!! So thx for that.
BUT I now also see the difference, I have a regular Azure AD in my original tenant and not a B2C one.

So creating a new tenant with the B2C option will indeed work ( like your video and sample ), but Azure AD does not :/

**Comment by VladislavAntonyuk** [comment]
Hmm, there shouldn't be any differences. I will try it as well.

it looks like I can become a video blogger 😄

**Comment by VladislavAntonyuk** [comment]
@Depechie the new video for you: https://youtu.be/3RGX5mVRXSs

**Comment by Depechie** [comment]
Awesome! Will take a look later this week, currently at an event for a few days.

**Comment by Depechie** [comment]
Hey @VladislavAntonyuk ok this does indeed work!! Thanks again for the tutorials.

**Comment by VladislavAntonyuk** [comment]
@Depechie Just wondering what you missed while setting up AD?

**Comment by Depechie** [comment]
I went for: Accounts in this organisational directory only ( single tenant ).

Because I wanted to restrict access only to those users I manually added to Azure AD itself, instead of letting anybody join.
