### ISSUE TITLE
System.DllNotFoundException: 'e_sqlite3'

### ISSUE THREAD

**Issue by rbsdotnet** [VladislavAntonyuk/MauiSamples#2]
hi 

when use in ios , error System.DllNotFoundException: 'e_sqlite3'
<img width="1920" alt="e_sqlite3" src="https://user-images.githubusercontent.com/49598914/152201254-1121f76c-5fa0-4581-9a7c-1142cf5f32f2.png">

**Comment by VladislavAntonyuk** [comment]
could you please try the code from this branch: https://github.com/VladislavAntonyuk/MauiSamples/tree/sql-fix

**Comment by rbsdotnet** [comment]
Hi, 
Get this Branch , but error : System.TypeInitializationException: 'The type initializer for 'SQLite.SQLiteConnection' threw an exception.'


![image](https://user-images.githubusercontent.com/49598914/152459462-c6576a3e-56a2-4b1f-b874-bda2c790d4c8.png)

**Comment by VladislavAntonyuk** [comment]
Thank you, I will further investigate the issue.

**Comment by rbsdotnet** [comment]
Yes , it worked

![image](https://user-images.githubusercontent.com/49598914/152464270-9cb84623-55b8-4a8e-bff6-f8bee78b7e16.png)

**Comment by VladislavAntonyuk** [comment]
@rbsdotnet it is a known issue after updating Visual Studio to the latest preview. https://github.com/ericsink/SQLitePCL.raw/issues/468
