### ISSUE TITLE
iOS implementation limited to height of device with scrollview

### ISSUE THREAD

**Issue by bradyguyc** [VladislavAntonyuk/MauiSamples#200]
Do you know if the iOS implementation is limited to where if you have a scroll view as part of your view you are limited to the height of the device?  IE. scroll view won't work in iOS?   I have it working on android on emulator and device and scroll but iOS appears to be limited to the height of the screen.

**Comment by VladislavAntonyuk** [comment]
That is the problem of .NET MAUI ScrollView control. The scrolling doesn't work correctly on iOS.

**Comment by VladislavAntonyuk** [comment]
It should be fixed with the latest .NET MAUI 7 release

**Comment by bradyguyc** [comment]
Nice thanks for the insight. I updated last night and got distracted working on [RelayCommand] stuff.   I have the weirdest situations.   The [RelayCommand] only appears to work when I delete my bin and obj directories and rebuild.  It works once and then the 2nd build it's like that generator gets removed... [RelayCommand] is still in the code as it should be, be it appears the code generation stops work.....   So much fun.....   Thanks again for bottomsheet really like the component.

**Comment by VladislavAntonyuk** [comment]
There were changes in Source Generation code. You can create an issue in CommunityToolkit/dotnet repository
