### ISSUE TITLE
Dynamic FAB

### ISSUE THREAD

**Issue by bradyguyc** [VladislavAntonyuk/MauiSamples#202]
I implemented the FAB using the pattern you suggested in your post.  In the image you can see the FAB with a background of green.  The collectionview behind it has a tapgesturerecognizer on each item that pulls up the bottomsheet with details of each book.  The problem with the FAB is that the collectionview tap is recognized vs the button in the expander view content.   Any thoughts on how to resolve that?

Thanks

![image](https://user-images.githubusercontent.com/81129882/213025193-94b555f2-5eef-4d8a-b205-a074f8bf5f6d.png)

**Comment by VladislavAntonyuk** [comment]
Could you please attach a small repro?
There should not be a propagation of tap to collection view.

**Comment by bradyguyc** [comment]
I am working on the small repo.... it may take me awhile.... day job plus getting distracted with other parts of my app.   Thanks again....

**Comment by bradyguyc** [comment]
Discovered that the root problem was related to a complex layout I had in the grid where the expander was located.  Problem resolved.  Thanks this issue can be closed.
