### ISSUE TITLE
Gatt Callback error 4 - Can't connect to a device

### ISSUE THREAD

**Issue by zmehic** [VladislavAntonyuk/MauiSamples#249]
When I try to connect the app to my device using bluetooth I get an error saying: Gatt Callback error 4, I didn't make any code adjustements.
![335008255_145389074849819_4299079174395490265_n](https://user-images.githubusercontent.com/60481114/226426725-8751a02f-79dd-49fe-b734-d6b702569ed7.jpg)

**Comment by VladislavAntonyuk** [comment]
Try connect to your device using OS first. Maybe some pairing issues. If I am not mistaken in sample I use not secure connection
