### ISSUE TITLE
looking for version of KanbanBoard on its own that will build and run on windows and mac 

### ISSUE THREAD

**Issue by BlockchainPunks** [VladislavAntonyuk/MauiSamples#271]
looking for version of KanbanBoard on its own that will build and run on windows and mac - cannot get large project to build

do you have working version of KanbanBoard on its own that actually builds and runs first time

**Comment by VladislavAntonyuk** [comment]
KanbanBoard application works fine on both windows and mac
![image](https://user-images.githubusercontent.com/33021114/232190908-387728a1-e205-4144-a698-439d10e79d96.png)

**Comment by BlockchainPunks** [comment]
thanks - pulled again - cleaned then rebuilt - thanks
