### ISSUE TITLE
Very slow if I add  a lot of CustomPins

### ISSUE THREAD

**Issue by TFreudi1** [VladislavAntonyuk/MauiSamples#276]
Hello Vladislav, good job, but when I add arround 1000 custom pins the adding process  gets very slow and a lot of GC is happening.
I made my own logic now, but maybe there is a better solution.
The problem is  ... if I add the, lets say,  the tenth marker , your algorithm  deletes all the 9 that already added and added it again.
This get's worse the more markers you add.

**Comment by VladislavAntonyuk** [comment]
Hello @TFreudi1 , if you have only 1 Map, you can use static Pins/Markers in handler. In that case you don't need to recreate pins collection

**Comment by TFreudi1** [comment]
Hello Vladislav, that did'nt help . The problem is that, when I add 1 Pin , the handler is called with the complete list of all markers not only with the one I added, so I must clear the list, add ALL pins again ...   
<img width="857" alt="CustomPinProblem" src="https://user-images.githubusercontent.com/4739177/234607101-5b758e36-7e83-4c89-b265-1380a7b2ea0f.png">

**Comment by TFreudi1** [comment]
I prevent it with a new Pin-property called AddToList. So I add my arround 1000 custom pins with this set to false, then I change all my   CustomPins to AddToList to true, than I add a Dummy-Pin to trigger CustomMapHandler.AddPins, than I remove the dummy.

**Comment by VladislavAntonyuk** [comment]
You can compare list with existing pins and update only items that have changed.
Also if I am not mistaken line 52 (Markers.Clear) doesn’t remove pin from the map, you have to use for each and call Pin.Remove()

**Comment by davefxy** [comment]
I am seeing this issue also on the Android. I am seeing the correct number of pins when I add or remove pins. It is the number of Markers that never decreases. They just keep increasing. I am using your code in the Android CustomMapHandler. I added debug statements to the MapPins() method.

**Comment by VladislavAntonyuk** [comment]
Don't use `Markers.Clear`, each marker needs to be deleted by calling `marker.Remove()`

**Comment by davefxy** [comment]
@TFreudi1 Checkout the changes I made to the Android CustomMapHandler in the Discussions section about MapPins getting called twice each time a pin is added. I was able to eliminate the duplicate markers with a couple of simple changes to the way Markers is used.
