### ISSUE TITLE
Shell tool bar region is not seamless with page ? 

### ISSUE THREAD

**Issue by Strypper** [VladislavAntonyuk/MauiSamples#306]
Your result 
![image](https://github.com/VladislavAntonyuk/MauiSamples/assets/32596308/72fddba2-810e-49e3-98da-0cf0958ec38f)

My result
![image](https://github.com/VladislavAntonyuk/MauiSamples/assets/32596308/8476a9e0-a4cd-42ce-80cd-a197d988c91a)

**Comment by VladislavAntonyuk** [comment]
It uses page background color.

**Comment by Strypper** [comment]
> It uses page background color.

Ok, But it still a separate region right ? Do you have a solution to stretch the page to the top and bottom shell ?

**Comment by VladislavAntonyuk** [comment]
you can try setting the different background color here https://github.com/VladislavAntonyuk/MauiSamples/blob/main/MauiShellCustomization/Platforms/Android/CustomShellToolbarAppearanceTracker.cs#L22 and here https://github.com/VladislavAntonyuk/MauiSamples/blob/main/MauiShellCustomization/Platforms/Android/CustomShellBottomNavViewAppearanceTracker.cs#L42.

Technically you can access the page (find the rootView and then the page as a child) and set its layout params.
