### ISSUE TITLE
Drag issue in Mauipaint

### ISSUE THREAD

**Issue by jobmen** [VladislavAntonyuk/MauiSamples#372]
When I drag the. json file into the window, the file cannot be loaded. Is it related to my computer system settings?

**Comment by VladislavAntonyuk** [comment]
Maybe window control didn't correctly registered for drag and drop. Try restarting the app

**Comment by VladislavAntonyuk** [comment]
Not able to reproduce with .NET 8

**Comment by jobmen** [comment]
It doesn't work for my computer , Windows 11 22H2. 
I change another computer , the same result.
