### ISSUE TITLE
Card stack layout with flip card

### ISSUE THREAD

**Issue by erossini** [VladislavAntonyuk/MauiSamples#387]
Hi,
I'm looking at your code for the card stack layout and it is almost what I'm looking for 😁

Basically, I'm learning MAUI and I want to create an app with flash cards. So, I arrived at the point where I display the cards.

![image](https://github.com/VladislavAntonyuk/MauiSamples/assets/9497415/0f89fd34-e38e-4720-a189-d89a61109bb1)

Now, the problems I'm facing are:
- in the `CardView` I tried to change the `Content` but I get an error (`Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'`, different in Windows)
- if I add in the `CardView`  a `TapGesture`, the `SwipeGesture` or `PanGesture` are not effected the view, although they are fired.

```
var tapGesture = new TapGestureRecognizer();
tapGesture.Tapped += TapGesture_Tapped;
GestureRecognizers.Add(tapGesture);
```

Do you have any advice or code for that? Thank you in advance,
Enrico

**Comment by VladislavAntonyuk** [comment]
1. You can search for this issue in dotnet/MAUI repo. I saw it on Android. You cannot replace/reuse content. 
2. What do you mean by not affecting?

**Comment by erossini** [comment]
I put together a project as an example of the issue. You can find the project here https://github.com/erossini/MauiCardLayout

**Comment by VladislavAntonyuk** [comment]
@erossini from what I see PanGesture is executed and cards disappear and appear. TapGesture is executed as well and card flips. As for SwipeGesture, it is a known .NET MAUI issue.
You can see that CardView (CardLayout) already has a PanGesture:
var panGesture = new PanGestureRecognizer();
panGesture.PanUpdated += PanGesture_PanUpdated;
GestureRecognizers.Add(panGesture);

**Comment by VladislavAntonyuk** [comment]
Updated sample with some animations and tweaks
