### ISSUE TITLE
MauiTabView: IndicatorView+CarouselView issues

### ISSUE THREAD

**Issue by tranb3r** [VladislavAntonyuk/MauiSamples#397]
Hi,

I'd like to have a TabView header that looks like the TabbedPage header (icon+title ; tab header fills the whole width of the page).

So, two questions about the MauiTabView IndicatorView+CarouselView example:
- the Title binding in the IndicatorView does not work. Is there a fix for that?
- the IndicatorView is horizontally centered. Is there a way to make it fill the whole width of the page (in XF, FillAndExpand)?

Thanks

**Comment by VladislavAntonyuk** [comment]
1. https://github.com/xamarin/Xamarin.Forms/issues/9597 and https://github.com/xamarin/Xamarin.Forms/issues/10117. This is a possible solution: https://xamarinhowto.com/xamarin-forms-mvvm-datatemplate-with-indicatorview/
2. IndicatorView has a width property, so you can bind it to the page width

**Comment by tranb3r** [comment]
Thank you for your answer.

1. What do mean exactly? If there is a solution for this bug, could you please fix the MauiTabView sample?

2. If possible, could you please post a code example showing how to do that?

**Comment by VladislavAntonyuk** [comment]
It will be fixed by https://github.com/dotnet/maui/pull/19004

**Comment by tranb3r** [comment]
PR status is `stale`. Could you please take a look?

**Comment by tranb3r** [comment]
@VladislavAntonyuk 
PR is still `stale`.
Could you please take a look?

**Comment by VladislavAntonyuk** [comment]
PureWeen promised it will be included in March release of .NET MAUI. Nothing to do from my side

**Comment by tranb3r** [comment]
It does not look like it's been released...

**Comment by tranb3r** [comment]
@VladislavAntonyuk
It seems like the PR is still blocked. Is there anything we can do to get this fix? Thx.

**Comment by VladislavAntonyuk** [comment]
@tranb3r I showed different implementations. While that PR is on review you can use another solution

**Comment by tranb3r** [comment]
> @tranb3r I showed different implementations. While that PR is on review you can use another solution

I know there are other implementations, but as explained in this issue, the Title binding in the IndicatorView does not work, which means it's not possible to create a nice TabView header with IndicatorView+CarouselView.

So my question is: what has to be done to finally get this fixed?
