### ISSUE TITLE
Kanbas board - Errror: Layout cycle detected

### ISSUE THREAD

**Issue by nnovalbos** [VladislavAntonyuk/MauiSamples#398]
Hello,

I am trying to run the example on windows and I am getting the following error:
```

    {Microsoft.UI.Xaml.UnhandledExceptionEventArgs}
    Exception: {"A cycle occurred while laying out the GUI."}
    Handled: false
    Message: "Layout cycle detected.  Layout could not complete."
```

I attach an image of the dependencies I am using. I don't know if anything extra needs to be done to be able to run the example.

Thank you!

![error](https://github.com/VladislavAntonyuk/MauiSamples/assets/34722108/20e8733d-3a47-454f-b912-eb1ce3be0de9)

**Comment by VladislavAntonyuk** [comment]
Let's wait for the final .NET 8 GA. the issue should be fixed after that

**Comment by VladislavAntonyuk** [comment]
Unfortunately, it's a .NET MAUI issue related to Windows CarouselView ItemTemplate. The app will run if you comment `<CarouselView.ItemTemplate>`.
You can open the issue in .NET MAUI repo
