### ISSUE TITLE
MauiTaskListApp crashes in release mode

### ISSUE THREAD

**Issue by ewoody** [VladislavAntonyuk/MauiSamples#413]
MauiTaskListApp crashes after splash screen in release mode on device

**Comment by VladislavAntonyuk** [comment]
please provide details about your device

**Comment by ewoody** [comment]
iPhone 15Sent from my iPhoneOn 15 Feb 2024, at 19:26, Vladislav Antonyuk ***@***.***> wrote:﻿
please provide details about your device

**Comment by VladislavAntonyuk** [comment]
https://github.com/dotnet/efcore/issues/32496
