### ISSUE TITLE
`<Span>`s and support for setting custom cursors

### ISSUE THREAD

**Issue by MartyIX** [VladislavAntonyuk/MauiSamples#421]
I have noticed that [`Span`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.span?view=net-maui-8.0) is not a [`VisualElement`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.visualelement?view=net-maui-8.0). So this `if` is not true:

https://github.com/VladislavAntonyuk/MauiSamples/blob/c774f4d3230f546e5dd74abb34c9e697522ea45a/MauiCursor/CursorBehavior.cs#L9

@VladislavAntonyuk Would you please know how to modify the code to allow custom cursors for `<Span>`s?

**Comment by VladislavAntonyuk** [comment]
You can see how TextColor or other properties implemented. Span should be an Element or View.

**Comment by VladislavAntonyuk** [comment]
Even Native TextBlock doesn't allow custom cursor. Run, Span are not UIElement, they are TextElement.
```
TextBlock textBlock = new TextBlock();
textBlock.IsTextSelectionEnabled = true;
textBlock.FontFamily = new FontFamily("Arial");

// For Run and Span, add 'using Windows.UI.Xaml.Documents;'
var run = new Run();
run.Text = "This text demonstrates ";

var span = new Microsoft.UI.Xaml.Documents.Span();

Run run1 = new Run();
run1.FontStyle = Windows.UI.Text.FontStyle.Italic;
run1.Text = "the use of inlines ";

Run run2 = new Run();
run2.Text = "with formatting.";

span.Inlines.Add(run1);
span.Inlines.Add(run2);
textBlock.Inlines.Add(run);
textBlock.Inlines.Add(span);

// Add TextBlock to the visual tree.
return textBlock;
```
