### ISSUE TITLE
Cutom cursor

### ISSUE THREAD

**Issue by eduardoagr** [VladislavAntonyuk/MauiSamples#425]
Let me tell you that I admire you. 
Glory to Ukraine, stay strong.

tried out the custom cursor in my project., but it doesn't work the first time.

[https://reccloud.com/u/h6960fq](url)

can you help me

**Comment by eduardoagr** [comment]
https://reccloud.com/u/h6960fq

**Comment by VladislavAntonyuk** [comment]
Thank you @eduardoagr 
If possible could you create a small reproduction project on github? It will be much easier to reproduce and resolve the issue.

**Comment by VladislavAntonyuk** [comment]
the suggestion for you is not set it on hover, but on initialization, since you know the expected cursor for this control.
```
<Label
	mauiCursor:CursorBehavior.Cursor="IBeam"/>
```
