### ISSUE TITLE
Update CustomMapHander (for iOS) to .NET 9

### ISSUE THREAD

**Issue by patkozlowski** [VladislavAntonyuk/MauiSamples#442]
See [fix](https://github.com/dotnet/maui/issues/20612#issuecomment-2489769439) for CustomMapHander.cs for iOS as .Net 9 changed how handlers work.  Not sure if your other handlers are affected.  This one just affected me when changing icon in the handlers.

**Comment by VladislavAntonyuk** [comment]
Good catch, I forgot to override DisconnectHandler
