### ISSUE TITLE
Add MapCallbackHandler in android 

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [VladislavAntonyuk/MauiSamples#443]
@VladislavAntonyuk  hello , you need to add this class 

public class MapCallbackHandler : Java.Lang.Object, IOnMapReadyCallback
{
    private readonly CustomMapHandler mapHandler;

    public MapCallbackHandler(CustomMapHandler mapHandler)
    {
        this.mapHandler = mapHandler;
    }

    public void OnMapReady(GoogleMap googleMap)
    {
        mapHandler.UpdateValue(nameof(MapEx.CustomPins));
        googleMap.MarkerClick += mapHandler.MarkerClick;
    }
}

to CustomMapHandler in android project

**Comment by VladislavAntonyuk** [comment]
Hello @AhmedAdelGadElkareeem , why do I need it? I have event listeners that do the same as your MarkerClick event subscription.

**Comment by AhmedAdelGadElkareeem** [comment]
sorry for this mistake i not noticed that you alread added it
