### ISSUE TITLE
where is add sqlite db?

### ISSUE THREAD

**Issue by hamidish** [VladislavAntonyuk/MauiSamples#6]
hi
where is add db in maui?
in resources or in each paltfrom?

**Comment by VladislavAntonyuk** [comment]
https://github.com/VladislavAntonyuk/MauiSamples/blob/main/Sqlite/SqliteRepository/AccountRepository.cs

Hi, you set the path to database. The database is usually stored in the device storage.

**Comment by hamidish** [comment]
> https://github.com/VladislavAntonyuk/MauiSamples/blob/b139a9ef22e3bdbbb032dbc836e2aa83ba15873f/Sqlite/SqliteRepository/AccountRepository.cs#L12
> 
> Hi, you set the path to database. The database is usually stored in the device storage.

meand, I do not save in the project ؟

**Comment by hamidish** [comment]
i got this error :
SQLite.SQLiteException
  Message=no such table:

**Comment by hamidish** [comment]
i go to project folder in obj in android folder paste my db to assets. its true?

**Comment by VladislavAntonyuk** [comment]
No, your database should be on your Android device

**Comment by VladislavAntonyuk** [comment]
> 

But you still have to read it. You have to pass correct path to db.

**Comment by VladislavAntonyuk** [comment]
> > https://github.com/VladislavAntonyuk/MauiSamples/blob/b139a9ef22e3bdbbb032dbc836e2aa83ba15873f/Sqlite/SqliteRepository/AccountRepository.cs#L12
> > 
> > Hi, you set the path to database. The database is usually stored in the device storage.
> 
> means, I do not save in the project ؟

But you still have to read it. You have to pass correct path to db.

**Comment by VladislavAntonyuk** [comment]
Similar discussion: https://vladislavantonyuk.azurewebsites.net/articles/Adding-SQLite-to-the-.NET-MAUI-application#comment-5688469148

**Comment by hamidish** [comment]
thx.
i used exitnig sqlite db.
but now i creattable from with code and now its worked

**Comment by VladislavAntonyuk** [comment]
@hamidish does the issue solved? can I close it?
